# Generated by Django 3.1.2 on 2020-11-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='store',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
