# Generated by Django 3.1.2 on 2020-11-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_exam_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correctimg',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='optionimg1',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='optionimg2',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='optionimg3',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='optionimg4',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
