# Generated by Django 3.1.2 on 2020-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20201114_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='correct',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='option1',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='option2',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='option3',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='exam',
            name='option4',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
