# Generated by Django 3.1.2 on 2020-12-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20201223_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
