# Generated by Django 3.1.2 on 2020-12-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20201223_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='examans',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
