# Generated by Django 3.1.2 on 2020-12-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_examans_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_name',
            field=models.SlugField(max_length=1000),
        ),
    ]
