# Generated by Django 3.1.2 on 2020-12-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20201224_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
