# Generated by Django 3.1.2 on 2020-12-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_auto_20201224_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
