# Generated by Django 3.1.2 on 2020-12-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_auto_20201231_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_end_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
