# Generated by Django 3.1.2 on 2020-12-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_tests_test_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
