# Generated by Django 3.1.2 on 2020-12-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20210101_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_res',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student_res',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student_res',
            name='password',
        ),
    ]
