# Generated by Django 3.1.2 on 2020-12-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_auto_20210101_0123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_res',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='register',
        ),
    ]
