# Generated by Django 3.1.2 on 2021-01-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('exam', '0031_auto_20210101_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='std',
            field=models.CharField(blank=True, choices=[('11th', '11th'), ('12th', '12th'), ('other', 'other')], default='11th', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student_res')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.tests')),
            ],
        ),
    ]
