# Generated by Django 3.1.2 on 2021-01-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_auto_20210101_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='time',
            field=models.TimeField(default='00:59:00'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='std',
            field=models.CharField(blank=True, choices=[('11th', '11th'), ('12th', '12th'), ('other', 'other')], max_length=30, null=True),
        ),
    ]
