# Generated by Django 3.1.2 on 2021-01-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0034_auto_20210102_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='time',
            field=models.CharField(default='59:00', max_length=8),
        ),
    ]
