# Generated by Django 3.1.2 on 2021-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_auto_20210103_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='end_time',
            field=models.BooleanField(default=False),
        ),
    ]
