# Generated by Django 3.1.2 on 2021-01-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_tests_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='end_time',
            new_name='end_test',
        ),
    ]
