# Generated by Django 3.1.2 on 2021-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_auto_20210105_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='end_test',
        ),
        migrations.AddField(
            model_name='registers',
            name='end_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registers',
            name='time',
            field=models.CharField(default='59', max_length=200),
        ),
    ]
