# Generated by Django 3.1.2 on 2021-01-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_auto_20210105_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='time',
            field=models.CharField(blank=True, default='59', max_length=200, null=True),
        ),
    ]
