# Generated by Django 3.1.2 on 2021-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0042_auto_20210109_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='time',
            field=models.CharField(blank=True, default='59:00', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_date',
            field=models.DateField(blank=True, max_length=500, null=True),
        ),
    ]
